#!/bin/bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024-present Scalytics, Inc. (https://www.scalytics.io)
# Caddy web server configuration module
# This sets up Caddy as a secure, automated reverse proxy.

# Check if core utils have been sourced. If not, source them.
if [[ -z $(type -t log) ]]; then
  MODULE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
  source "$MODULE_DIR/utils.sh"
  source "$MODULE_DIR/env.sh"
fi

# stop and disable other webservers
stop_other_webservers() {
  log "Checking for other webservers..."
  if systemctl is-active --quiet nginx; then
    log "Stopping and disabling Caddy..."
    run_with_sudo systemctl stop nginx
    run_with_sudo systemctl disable nginx
    log_success "Caddy stopped and disabled."
  fi

  if systemctl is-active --quiet apache2; then
    log "Stopping and disabling Apache2..."
    run_with_sudo systemctl stop apache2
    run_with_sudo systemctl disable apache2
    log_success "Apache2 stopped and disabled."
  fi
}

# install Caddy
install_caddy() {
  if command_exists caddy; then
    log_success "Caddy is already installed."
    return 0
  fi

  log "Installing Caddy..."

  local prereqs=("debian-keyring" "debian-archive-keyring" "apt-transport-https" "curl")
  local missing_prereqs=()
  for pkg in "${prereqs[@]}"; do
    if ! dpkg -s "$pkg" &>/dev/null; then
      missing_prereqs+=("$pkg")
    fi
  done

  if [ ${#missing_prereqs[@]} -gt 0 ]; then
    log "Installing prerequisite packages: ${missing_prereqs[*]}"
    run_with_sudo apt-get update
    run_with_sudo apt-get install -y "${missing_prereqs[@]}"
  fi

  local gpg_key_url='https://dl.cloudsmith.io/public/caddy/stable/gpg.key'
  local temp_key_path='/tmp/caddy-stable-archive-keyring.gpg'
  local final_key_path='/usr/share/keyrings/caddy-stable-archive-keyring.gpg'
  curl -1sLf "$gpg_key_url" -o "$temp_key_path"
  run_with_sudo gpg --dearmor < "$temp_key_path" > "${final_key_path}.tmp"
  run_with_sudo mv "${final_key_path}.tmp" "$final_key_path"
  rm -f "$temp_key_path"

  run_with_sudo curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | run_with_sudo tee /etc/apt/sources.list.d/caddy-stable.list > /dev/null
  run_with_sudo apt-get update
  if run_with_sudo apt-get install -y caddy; then
    log_success "Caddy installed successfully."
  else
    log_error "Failed to install Caddy."
    return 1
  fi
}

apply_system_tuning() {
  log "Applying system-level performance tuning for Caddy..."

  local sysctl_config_file="/etc/sysctl.d/99-caddy-optimizations.conf"
  log "Creating sysctl config at $sysctl_config_file..."
  echo "net.core.somaxconn=65535" | run_with_sudo tee "$sysctl_config_file" > /dev/null
  echo "net.ipv4.ip_local_port_range=1024 65000" | run_with_sudo tee -a "$sysctl_config_file" > /dev/null

  if run_with_sudo sysctl -p "$sysctl_config_file"; then
    log_success "Sysctl settings applied."
  else
    log_warning "Failed to apply sysctl settings."
  fi

  local systemd_override_dir="/etc/systemd/system/caddy.service.d"
  local systemd_override_file="$systemd_override_dir/override.conf"
  log "Configuring ulimit for Caddy service..."
  run_with_sudo mkdir -p "$systemd_override_dir"
  echo "[Service]" | run_with_sudo tee "$systemd_override_file" > /dev/null
  echo "LimitNOFILE=65535" | run_with_sudo tee -a "$systemd_override_file" > /dev/null

  run_with_sudo systemctl daemon-reload
  log_success "Systemd override for Caddy created. Limits will apply on next restart."
}

# configure Caddy
configure_caddy() {
  local domain_to_use="$1"
  if [ -z "$domain_to_use" ]; then
    log_error "configure_caddy requires a domain name argument."
    return 1
  fi

  stop_other_webservers
  install_caddy || return 1
  apply_system_tuning || log_warning "System tuning failed, but continuing."

  log "Configuring Caddy for $domain_to_use..."

  APP_NAME="${APP_NAME:-connect}"
  PORT="${PORT:-3000}"

  local caddyfile_path="/etc/caddy/Caddyfile"
  local temp_caddyfile=$(mktemp)

  log "Deploying custom 502 error page..."
  local error_page_src="$MODULE_DIR/../templates/502.html"
  local error_page_dest_dir="$APP_DIR/public_static"
  local error_page_dest_file="$error_page_dest_dir/502.html"

  run_with_sudo mkdir -p "$error_page_dest_dir"
  run_with_sudo cp "$error_page_src" "$error_page_dest_file"
  run_with_sudo chown caddy:caddy "$error_page_dest_file"
  run_with_sudo chmod 644 "$error_page_dest_file"
  log_success "Custom 502 error page deployed to $error_page_dest_file"

  cat > "$temp_caddyfile" << EOF
# Caddyfile for $domain_to_use
# Generated by Connect deployment system

{
    email ${SSL_EMAIL:-admin@$domain_to_use}
}

$domain_to_use {
    request_body {
        max_size 2048m
    }

    encode gzip zstd

    header {
        Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "SAMEORIGIN"
        X-XSS-Protection "1; mode=block"
        Referrer-Policy "strict-origin-when-cross-origin"
        Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self' https://huggingface.co ws: wss:; object-src 'none'; frame-ancestors 'self'; form-action 'self'; base-uri 'self'"
        Permissions-Policy "geolocation=(), microphone=(), camera=(), payment=()"
        -Server
    }

    @badBots header User-Agent (?i)(curl|wget|python-requests|Python-urllib|nikto|sqlmap|sirepuB|sqlninja|arachni|dirbuster|nmap|metasploit)
    respond @badBots 403

    @blockedPaths path_regexp \.(git|env|htaccess|svn)$|/(wp-admin|wp-login|phpMyAdmin|phpmyadmin)
    respond @blockedPaths 404

    handle_errors {
    @api502 {
        expression {http.error.status_code} == 502
        path /api/*
    }
    handle @api502 {
        header Content-Type application/json
        respond "The service is temporarily unavailable. Please try again later." 502
    }

    @html502 expression {http.error.status_code} == 502
    rewrite @html502 /502.html
    root * ${APP_DIR}/public_static
    file_server
    } 

    handle_path /research_tasks/*/stream* {
        reverse_proxy http://127.0.0.1:8001 {
            # SSE-specific settings
            header_up Connection "keep-alive"
            transport http {
                read_timeout 0
                write_timeout 0
                keepalive 30m
                dial_timeout 10s
            }
            flush_interval 0s
            
            # Health checks are disabled for the stream as it's a long-lived connection
            # and the application has its own heartbeat/error handling.
            
            # Load balancing policy
            lb_policy round_robin
            lb_try_duration 5s
            lb_try_interval 250ms
        }
    }

    handle /api-docs {
        rewrite * /api-docs.html
        root * $APP_DIR/docs
        file_server
    }

    handle {
        reverse_proxy localhost:$PORT
    }

    log {
        output file /var/log/caddy/access.log {
            roll_size 100mb
            roll_keep 10
            roll_keep_for 720h
        }
        format json
    }
}
EOF

  log "Validating new Caddyfile configuration..."
  if ! run_with_sudo caddy validate --config "$temp_caddyfile" --adapter caddyfile; then
    log_error "Generated Caddyfile is invalid. Aborting configuration."
    rm "$temp_caddyfile"
    return 1
  fi
  log_success "Caddyfile validation passed."

  log "Applying new Caddyfile configuration..."
  run_with_sudo mv "$temp_caddyfile" "$caddyfile_path"

  run_with_sudo mkdir -p /var/log/caddy
  run_with_sudo touch /var/log/caddy/access.log
  run_with_sudo chown -R caddy:caddy /var/log/caddy
  run_with_sudo chmod 644 /var/log/caddy/access.log

  run_with_sudo chown caddy:caddy "$caddyfile_path"
  run_with_sudo chmod 644 "$caddyfile_path"

  if run_with_sudo caddy fmt --overwrite "$caddyfile_path"; then
    log_success "Caddyfile formatted successfully."
  else
    log_warning "Could not format Caddyfile, continuing anyway."
  fi

  log "Restarting Caddy service with new configuration..."
  if run_with_sudo systemctl restart caddy; then
    log_success "Caddy service restarted successfully for $domain_to_use."
  else
    log_error "Failed to restart Caddy service. Check status with 'systemctl status caddy'."
    return 1
  fi

  return 0
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  show_header
  setup_environment
  configure_caddy "$@"
fi
